orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@1.3.0
version: 2.1

# --------------------------------
# common : executors
# --------------------------------

executors:
  node:
    docker:
      - image: cimg/node:12.18.3
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD

commands:
  lint:
    description: "lint"
    steps:
      - run:
          name: "Lint"
          command: npm run lint
  audit:
    description: "Audit npm dependencies"
    steps:
      - run:
          name: "Audit npm dependencies"
          command: npm run audit:critical
  test:
    description: "run unit tests"
    steps:
      - run:
          name: "Run unit tests"
          command: npm run _test:ci
  build:
    description: "build the application"
    steps:
      - run:
          name: Build the application
          command: npm run build:package
  cdk-synth:
    description: "synthesize cdk"
    steps:
      - run:
          name: CDK synth
          command: npm run cdk:synth
  deploy-stack:
    description: "deploy the stack"
    parameters:
      stage:
        type: string
    steps:
      - run:
          name: Deploy for stage << parameters.stage >>
          command: npm run _deploy:<< parameters.stage >>:ci

jobs:
  test-build:
    executor: node
    steps:
      - checkout
      - node/install-packages
      - audit
      - lint
      - test
      - build
      - persist_to_workspace:
          root: .
          paths:
            - dist
  deploy-production-stack:
    executor: node
    steps:
      - checkout
      - node/install-packages
      - attach_workspace:
          at: .
      - aws-cli/setup
      - cdk-synth
      - deploy-stack:
          stage: "production"

workflows:
  test-build-deploy:
    jobs:
      - test-build:
          context: dockerhub_credentials
      - deploy-production-stack:
          context: dockerhub_credentials
          requires:
            - test-build
          filters:
            branches:
              only:
                - master
